lib/charms/glauth_k8s/v0/ldap.py

This pull request tries to present the preliminary version of the juju charm library for the `ldap` juju interface. This version implements fundamental provider, consumer, and juju custom events.
**Note** that this juju charm library is subject to change once the design of the `glauth-k8s` charm is finalized.

feat: initial version of the ldap interface

---

metadata.yaml
src/database.py

This PR updates the `groups` table name to `ldapgroups` to include the breaking change from v2.3.0.
Check https://github.com/canonical/glauth-utils/pull/8 for testing instructions.

fix: update tablename

---

.pre-commit-config.yaml
README.md
config.yaml
lib/charms/glauth_k8s/v0/ldap.py
metadata.yaml
src/charm.py
src/configs.py
src/database.py
src/integrations.py
src/utils.py
templates/glauth.cfg.j2
tests/integration/test_charm.py
tests/unit/conftest.py
tests/unit/test_charm.py
tests/unit/test_utils.py

This pull request tries to support the GLAuth upstream's StartTLS functionality.

feat: enable StartTLS support

---

src/loki_alert_rules/glauth_high_severity_log.rule

This PR simply adds a LogQL `label filter` to avoid loki processing log entry that failed json parsing.

fix(loki-rule): improve error handling in json parsing

---

tests/integration/conftest.py
tests/integration/test_charm.py
tests/integration/tester.py

This pull request uses the `any-charm` to add more integration tests to cover multiple juju integrations required/offered by `glauth-k8s` charmed operator.

test: add integration testcases

---

lib/charms/glauth_k8s/v0/ldap.py
metadata.yaml
src/charm.py
src/integrations.py
tests/integration/test_charm.py
tests/unit/test_charm.py

This pull request tries to use the Juju secret to encapsulate the bind account password passed to the requirer charm. The main logic is generally done in the `ldap` charm library so that the provider charm does not need to know it.
Please note that I intentionally leave the requirer side this time. Will chat with the stakeholders about how they wanna deal with the secret.

feat: apply juju secrets to transfer bind account password

---

.github/workflows/on_schedule.yaml
.github/workflows/update_libs.yaml
.pre-commit-config.yaml
lib/charms/certificate_transfer_interface/v0/certificate_transfer.py
lib/charms/loki_k8s/v0/loki_push_api.py
lib/charms/observability_libs/v1/cert_handler.py
lib/charms/prometheus_k8s/v0/prometheus_scrape.py
lib/charms/tls_certificates_interface/v3/tls_certificates.py
metadata.yaml
src/charm.py
src/integrations.py
tests/unit/conftest.py
tox.ini

- Add workflow for updating the charm libs
- Update charm libs
- Start using cert_handler v1
- Remove peer relation, it was used only by cert_handler and v1 does not need it

Update charm libs

---

.pre-commit-config.yaml
CONTRIBUTING.md
fmt-requirements.txt
lint-requirements.txt
pyproject.toml
src/charm.py
src/configs.py
src/database.py
src/exceptions.py
src/integrations.py
src/utils.py
tests/unit/conftest.py
tests/unit/test_charm.py
tests/unit/test_utils.py
tox.ini

This pull request aims to replace black with ruff for formatting code.

chore: replace black with ruff as the formatter

---

.github/workflows/tests.yaml
lib/charms/glauth_k8s/v0/ldap.py
lib/charms/observability_libs/v1/cert_handler.py
lib/charms/tls_certificates_interface/v3/tls_certificates.py
src/charm.py
src/database.py
src/integrations.py
tests/integration/test_charm.py
tests/unit/conftest.py
tests/unit/test_charm.py

Fix ldap lib

---

tests/integration/conftest.py

This pull request aims to fix the [failing integration test](https://github.com/canonical/glauth-k8s-operator/actions/runs/11911261668/job/33194153802?pr=70) due to the breaking change introduced in the ops framework 2.17.0.
More details can be found [HERE](https://github.com/canonical/operator/releases/tag/2.17.0).

test: fix the integration test due to the juju secret id breaking changes

---

lib/charms/glauth_k8s/v0/ldap.py
src/database.py

This PR loose the constraints around the Pydantic dependency to allow versions bigger than `2.5.x`.
This change is required so other charms could use this charm's library, without needing to stick to Pydantic `2.5.x`

chose: loose Pydantic 2 version constraint

---

charmcraft.yaml
src/charm.py
src/configs.py
templates/glauth.cfg.j2

`anonymousdse` must be enabled for applications like SSSD to successfully bind to the Glauth server, but it's recommended to keep the option set to false if you're not using applications that need to anonymously query the root DSE. See the Glauth [Security](https://glauth.github.io/docs/security.html) documentation for more info. 
This option is needed for the SSSD operator in Charmed HPC to successfully bind to the Glauth service, otherwise the SSSD service will silently fail in background with the error message `Insufficient permissions (50)`. Once `anonymousdse` is enabled, SSSD successfully binds to Glauth if also using the patches provided in #78.

feat: add `anonymousdse_enabled` config option

---

.github/workflows/tests.yaml
src/charm.py
src/integrations.py
tests/integration/conftest.py
tests/integration/test_charm.py

This pull request tries to resolve the https://github.com/canonical/glauth-k8s-operator/issues/86.
The charm now will observe the events triggered from `ingress-per-unit` integration, and update the certificates correspondingly.

fix: update the tls certificate in ingress-per-unit integration

---

.gitignore
terraform/README.md
terraform/main.tf
terraform/outputs.tf
terraform/variables.tf
terraform/versions.tf

This PR adds a Terraform module for deploying glauth-k8s. The module can be used like so to deploy the glauth-k8s charm in a k8s cloud:
```terraform
terraform {
required_providers {
juju = {
source  = "juju/juju"
version = ">= 0.16.0"
}
}
}
provider "juju" {}
resource "juju_model" "idm" {
name = "idm-stack"
}
module glauth-k8s {
source = "git::https://github.com/canonical/glauth-k8s-operator//terraform"
module_name = juju_model.idm.name
}
```
We need this module since it makes it much easier to deploy glauth-k8s with our HPC charms + integrate with SSSD.

feat: add module for deploying glauth-k8s with terraform 

---

tests/integration/conftest.py
tests/integration/test_charm.py
tests/integration/tester.py

This pull request adds an integration test to simulate an LDAP client charm workload that executes the StartTLS & search operation.

test: simulate StartTLS operation in any-charm tester

---

README.md
charmcraft.yaml
src/charm.py
src/integrations.py
tests/integration/test_charm.py

This pull request removes the hostname charm configuration for the following reasons:
- The `hostname` config was initially introduced when the charm was developed, before ingress came into the picture. With ingress now in place, `hostname` is redundant and may cause confusion for clients as it overlaps with the ingress host.
- Kubernetes service DNS or the ingress hostname/IP already provides a stable address for glauth units, eliminating the need for an additional configuration parameter.
- The CertHandler component can cause TLS private key and certificate mismatches when `hostname` is updated, leading to potential out-of-sync issues. This also raises a separate consideration: replacing `CertHandler` with the `tls-certificate` v4 library for improved reliability.
By removing …

refactor: remove the charm config `hostname`

---

.github/workflows/tests.yaml
lib/charms/glauth_k8s/v0/ldap.py
tests/integration/conftest.py
tests/integration/db.sql
tests/integration/test_charm.py
tests/unit/test_ldap_requirer.py
tox.ini

IAM-1284
Adds support for pydantic v1 in the ldap library. The compatibility layer in the `ldap` library is quite hacky and custom to our use, if someone has a better solution I'd be happy to change it.
The integration tests with any charm will now run for both v1 and v2 pydantic. Also added a new tox environment so that the unit tests can run for v1 as well. I did not apply the same logic for the auxiliary relation, as v1 support shouldn't be required there.

Add pydantic V1 support

---

terraform/main.tf

`trust` must be set to true since the operator accesses the Kubernetes API. Without this option set in the Terraform module, glauth-k8s will fail to deploy as part of a Terraform plan.

fix: add `trust = true` to tf module

---

src/integrations.py
tests/integration/test_charm.py

In #103 I forgot to conditionally add the ldaps_urls.
The `ldaps_urls` was always added which should not be the case.
This PR fixes this and adds a test to ensure that the field is updated on config changed.

fix: Write ldaps_urls only if ldaps_enabled

---

charmcraft.yaml

Bumps the upstream source for the GLAuth oci image to the newly released 2.4.0.
Does this require a manual release of the image in Charmhub? I'm not sure if the CI also publishes that automatically.

chore: bump `upstream-source` for oci-image to 2.4.0

---

charmcraft.yaml

Since provides endpoints can be non-optional, can the default value of `optional` is [false](https://canonical-charmcraft.readthedocs-hosted.com/stable/reference/files/charmcraft-yaml-file/#endpoint-role-endpoint-name-optional), these endpoints are assumed non-optional.
Set `optional` flag on provides endpoints to indicate correct optionality.

Add optional flags to provides endpoints
